FROM node:22-alpine AS builder
WORKDIR /app
# Ensure node_modules is not copied from host
COPY package*.json ./
RUN rm -rf node_modules
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
